#!/bin/bash

# Update and upgrade system packages
update_system() {
    apt-get update && apt-get upgrade -y
}

# Install Python 3.12 and essential dependencies
install_python() {
    apt-get install -y software-properties-common
    add-apt-repository -y ppa:deadsnakes/ppa
    apt-get update
    apt-get install -y python3.10 python3.10-dev python3.10-venv python3-pip libpython3.10 libpython3.10-dev
}

# Install additional system dependencies
install_dependencies() {
    apt-get install -y --no-install-recommends \
        apt-utils aria2 curl zstd git libmagic-dev \
        locales mediainfo neofetch p7zip-full \
        p7zip-rar tzdata wget autoconf automake \
        build-essential cmake g++ gcc gettext \
        gpg-agent intltool libtool make unzip zip \
        libcurl4-openssl-dev libsodium-dev libssl-dev \
        libcrypto++-dev libc-ares-dev libsqlite3-dev \
        libfreeimage-dev swig libboost-all-dev \
        libpthread-stubs0-dev zlib1g-dev
}


# Install FFmpeg based on system architecture
install_ffmpeg() {
    ARCH=$(uname -m)
    mkdir -p /Temp
    cd /Temp

    case "$ARCH" in
        x86_64)
            wget https://github.com/5hojib/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-linux64-gpl-7.1.tar.xz
            ;;
        aarch64)
            wget https://github.com/5hojib/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-linuxarm64-gpl-7.1.tar.xz
            ;;
        *)
            echo "Unsupported architecture for FFmpeg: $ARCH"
            exit 1
            ;;
    esac

    7z x ffmpeg-n7.1-latest-linux*-gpl-7.1.tar.xz
    7z x ffmpeg-n7.1-latest-linux*-gpl-7.1.tar
    mv /Temp/ffmpeg-n7.1-latest-linux*/bin/ffmpeg /usr/bin/felix
    mv /Temp/ffmpeg-n7.1-latest-linux*/bin/ffprobe /usr/bin/ffprobe
    mv /Temp/ffmpeg-n7.1-latest-linux*/bin/ffplay /usr/bin/ffplay
    chmod +x /usr/bin/felix /usr/bin/ffprobe /usr/bin/ffplay
}



# Install Python packages
install_python_packages() {
    pip3 install --break-system-packages --no-cache-dir -U setuptools uv
}


# Clean up unnecessary packages and temporary files
cleanup() {
    apt-get remove -y \
        autoconf automake build-essential cmake g++ gcc gettext \
        gpg-agent intltool libtool make unzip zip libcurl4-openssl-dev \
        libssl-dev libc-ares-dev libsqlite3-dev swig libboost-all-dev \
        libpthread-stubs0-dev zlib1g-dev
    apt-get autoremove -y
    apt-get autoclean -y

    rm -rf /Temp Aeon Dockerfile
}

# Main script execution
main() {
    update_system
    install_python
    install_dependencies

    install_ffmpeg

    install_python_packages
    cleanup
}

main
